### ISSUE TITLE
Issue with Safari on iOS and desktop persists

### ISSUE THREAD

**Issue by rguikers** [uport-project/uport-lite#13]
Writing a new issue : 

Not working as expected on safari, getting the error again : Error: [uport-lite] while parsing data: '{"jsonrpc":"2.0","id":1,"result":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000221034cbe442ebfcfb2f7fabfa4d6f6dd92c7b90fe15e172a02f92649bb0000000000000000000000000000000000000000000000000000000000000"} ', error: TypeError: TypedArray.from requires its this argument subclass a TypedArray constructor

probably in function :

    if (body) body = new Buffer(new Uint8Array(body))
    originalCb(err, resp, body)
  }
but not sure..

Safari : Version 10.1 (12603.1.30.0.34)

**Comment by rguikers** [comment]
Above problem is still in base-x-bytearray. (line 75 in index.js ):

```
    if (ByteArray.name === 'Uint8Array') {
      // This handles an issue in safari
      return new Uint8Array(bytes.reverse())
    }
    return ByteArray.from(bytes.reverse())
```

is not working if ByteArray is undefined. changing the last line to :
```
return Buffer.from(bytes.reverse())
```
is a temporary fix for me now..

**Comment by pelle** [comment]
@rguikers Thanks. Investigating again
