### ISSUE TITLE
Duplicate infuraKey when used from uport-connect

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/uport-lite#22]
`uport-connect` is passing networks array as `opts` to the constructor. 

https://github.com/uport-project/uport-connect/blob/5871edf0a124fa35187bf1ac4e88c804fc362ebf/src/Connect.js#L87

It already has infuraKey in the url

https://github.com/uport-project/uport-transports/blob/develop/src/network/defaults.js

It is then added again here:

https://github.com/uport-project/uport-lite/blob/develop/src/index.js#L155

And we end up using `https://rinkeby.infura.io/v3/e72b472993ff46d3b5b88faa47214d7f/e72b472993ff46d3b5b88faa47214d7f` which throws an error.

**Comment by mi-xu** [comment]
Fixed by https://github.com/uport-project/uport-lite/pull/23
